# Setup
title:        CORe50
tagline:      A new Dataset and Benchmark for <br> <strong>Continuous Learning and Object Recognition</strong>
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Vincenzo Lomonaco
  url:        http://vincenzolomonaco.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
